# Generated by Django 5.0.6 on 2024-07-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource_Library',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_title', models.CharField(max_length=200)),
                ('resource_video', models.FileField(upload_to='')),
                ('resource_url', models.TextField()),
            ],
        ),
    ]
