# Generated by Django 5.0.6 on 2024-07-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_level_title', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_picture', models.ImageField(upload_to='')),
                ('course_progress', models.IntegerField()),
                ('course_content', models.TextField()),
                ('course_certificate', models.BooleanField()),
            ],
        ),
    ]
