# Generated by Django 5.0.6 on 2024-07-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_course_progress', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('level_of_education', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('achievement', models.TextField()),
                ('feedback', models.TextField()),
                ('current_course_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.courses')),
                ('teacher_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schools.schools')),
            ],
        ),
    ]
