# Generated by Django 5.0.6 on 2024-07-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='schools.schools')),
            ],
        ),
    ]
